name: 'Lucee Script Runner'
description: 'Run Lucee via the command line'
inputs:
  luceeVersion:
    description: Lucee Version to run, i.e. "light-6.2.2.91", "5.4.6.9", "zero-6.2.2.91"
    required: true
  luceeVersionQuery:
    description: Lucee Version Query to run (overrides luceeVersion, i.e. "5.4/stable/light", "6.1/snapshot/jar", "6/stable/zero" )
    default: ""
  webroot:
    description: webroot directory
    required: true
  execute:
    description: cfml script to execute
    required: true
  extensions:
    description: any additional extensions to install
    default: ""
  extensionDir:
    description: a directory containing any Lucee *.lex extentions to manually install
    default: ""
  compile:
    description: compile the cfml code under the webroot
    default: "false"
  antFlags:
    description: additional flags to pass to ant
    default: ""
  debugger:
    description: enable java debugging on port 5000 with suspend=y (not for CI, it will just hang waiting for you to connect a debugger)
    default: "false"
  luceeCFConfig:
    description: pass in a path to a complete .CFConfig.json file (not like configImport!)
    default: ""
  preCleanup:
    description: purge the directory Lucee is deployed into before starting
    default: "true"
  postCleanup:
    description: purge the directory Lucee is deployed into after finishing
    default: "true"
  uniqueWorkingDir:
    description: 'Working directory mode: "false" (default temp/lucee), "true" (auto-generate unique), or custom path (e.g., "/custom/work")'
    default: "false"
runs:
  using: "composite"
  steps:
    - if: runner.os != 'Windows'
      run: |
        pwd
        echo luceeVersion ${{ inputs.luceeVersion }}
        echo luceeVersionQuery ${{ inputs.luceeVersionQuery }}
        echo webroot ${{ inputs.webroot }}
        echo execute ${{ inputs.execute }}
        echo extensions ${{ inputs.extensions }}
        echo extensionDir ${{ inputs.extensionDir }}
        echo compile ${{ inputs.compile }}
        echo luceeCFConfig:${{inputs.luceeCFConfig}}
        ant -buildfile "${{ github.action_path }}/build.xml" ${{ inputs.antFlags }} -DluceeVersion="${{ inputs.luceeVersion }}" -DluceeVersionQuery="${{ inputs.luceeVersionQuery }}" \
          -Dwebroot="${{ inputs.webroot }}" -Dexecute="${{ inputs.execute }}" \
          -Dextensions="${{ inputs.extensions }}" -DextensionDir="${{ inputs.extensionDir }}" \
          -Dcompile="${{ inputs.compile }}" -Ddebugger="${{ inputs.debugger }}" \
          -DluceeCFConfig="${{inputs.luceeCFConfig}}" \
          -DpreCleanup="${{inputs.preCleanup}}" -DpostCleanup="${{inputs.postCleanup}}" \
          -DuniqueWorkingDir="${{inputs.uniqueWorkingDir}}"
      shell: bash
    - if: runner.os == 'Windows'
      run: |
        pwd
        echo luceeVersion ${{ inputs.luceeVersion }}
        echo luceeVersionQuery ${{ inputs.luceeVersionQuery }}
        echo webroot ${{ inputs.webroot }}
        echo execute ${{ inputs.execute }}
        echo extensions ${{ inputs.extensions }}
        echo extensionDir ${{ inputs.extensionDir }}
        echo compile ${{ inputs.compile }}
        echo luceeCFConfig:${{inputs.luceeCFConfig}}
        ant -buildfile "${{ github.action_path }}/build.xml" ${{ inputs.antFlags }} ^
        -DluceeVersion="${{ inputs.luceeVersion }}" -DluceeVersionQuery="${{ inputs.luceeVersionQuery }}" ^
         -Dwebroot="${{ inputs.webroot }}" -Dexecute="${{ inputs.execute }}" -Dextensions="${{ inputs.extensions }}" ^
         -DextensionDir="${{ inputs.extensionDir }}" -Dcompile="${{ inputs.compile }}" ^
         -Ddebugger="${{ inputs.debugger }}" -DluceeCFConfig="${{inputs.luceeCFConfig}}" ^
         -DpreCleanup="${{inputs.preCleanup}}" -DpostCleanup="${{inputs.postCleanup}}" ^
         -DuniqueWorkingDir="${{inputs.uniqueWorkingDir}}"
      shell: cmd
